/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Fondos
        "bg-base":     "var(--color-bg-base)",
        "bg-subtle":   "var(--color-bg-subtle)",
        "bg-muted":    "var(--color-bg-muted)",
        "surface-1":   "var(--color-surface-1)",
        "surface-2":   "var(--color-surface-2)",
        "surface-3":   "var(--color-surface-3)",
        // Bordes
        "border-subtle":  "var(--color-border-subtle)",
        "border-default": "var(--color-border-default)",
        "border-strong":  "var(--color-border-strong)",
        // Texto
        "text-primary":   "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-tertiary":  "var(--color-text-tertiary)",
        "text-disabled":  "var(--color-text-disabled)",
        "text-inverse":   "var(--color-text-inverse)",
        // Acento
        "accent":         "var(--color-accent)",
        "accent-hover":   "var(--color-accent-hover)",
        "accent-light":   "var(--color-accent-light)",
        "accent-muted":   "var(--color-accent-muted)",
        // Highlight
        "highlight":      "var(--color-highlight)",
        "highlight-bg":   "var(--color-highlight-bg)",
        "highlight-muted":"var(--color-highlight-muted)",
      },
      fontFamily: {
        sans:    ["var(--font-sans)"],
        display: ["var(--font-display)"],
        mono:    ["var(--font-mono)"],
      },
      fontSize: {
        "tli-xs":   "var(--text-xs)",
        "tli-sm":   "var(--text-sm)",
        "tli-base": "var(--text-base)",
        "tli-md":   "var(--text-md)",
        "tli-lg":   "var(--text-lg)",
        "tli-xl":   "var(--text-xl)",
        "tli-2xl":  "var(--text-2xl)",
        "tli-3xl":  "var(--text-3xl)",
        "tli-4xl":  "var(--text-4xl)",
        "tli-5xl":  "var(--text-5xl)",
      },
      spacing: {
        "0-5":  "var(--space-0-5)",
        "1":    "var(--space-1)",
        "1-5":  "var(--space-1-5)",
        "2":    "var(--space-2)",
        "3":    "var(--space-3)",
        "4":    "var(--space-4)",
        "5":    "var(--space-5)",
        "6":    "var(--space-6)",
        "8":    "var(--space-8)",
        "10":   "var(--space-10)",
        "12":   "var(--space-12)",
        "16":   "var(--space-16)",
        "20":   "var(--space-20)",
        "24":   "var(--space-24)",
        "32":   "var(--space-32)",
        "40":   "var(--space-40)",
        "48":   "var(--space-48)",
        "64":   "var(--space-64)",
      },
      borderRadius: {
        "tli-sm":   "var(--radius-sm)",
        "tli-base": "var(--radius-base)",
        "tli-md":   "var(--radius-md)",
        "tli-lg":   "var(--radius-lg)",
        "tli-xl":   "var(--radius-xl)",
        "tli-2xl":  "var(--radius-2xl)",
      },
      boxShadow: {
        "xs":        "var(--shadow-xs)",
        "sm":        "var(--shadow-sm)",
        "md":        "var(--shadow-md)",
        "lg":        "var(--shadow-lg)",
        "xl":        "var(--shadow-xl)",
        "2xl":       "var(--shadow-2xl)",
        "accent-sm": "var(--shadow-accent-sm)",
        "accent-md": "var(--shadow-accent-md)",
        "inset":     "var(--shadow-inset)",
      },
      transitionTimingFunction: {
        "premium": "var(--ease-premium)",
        "spring":  "var(--ease-spring)",
      },
      transitionDuration: {
        "fast":    "var(--duration-fast)",
        "base":    "var(--duration-base)",
        "slow":    "var(--duration-slow)",
        "slower":  "var(--duration-slower)",
        "slowest": "var(--duration-slowest)",
      },
      zIndex: {
        "raised":   "var(--z-raised)",
        "dropdown": "var(--z-dropdown)",
        "sticky":   "var(--z-sticky)",
        "overlay":  "var(--z-overlay)",
        "modal":    "var(--z-modal)",
        "toast":    "var(--z-toast)",
      },
      maxWidth: {
        "container-sm":  "var(--container-sm)",
        "container-md":  "var(--container-md)",
        "container-lg":  "var(--container-lg)",
        "container-xl":  "var(--container-xl)",
        "container-2xl": "var(--container-2xl)",
      },
    },
  },
  plugins: [],
};
